title: BREADitor
description: A Photoshop-ish editor for your game assets that you can extend if you know JS!
google_analytics: 
show_downloads: true
theme: jekyll-theme-tactile

gems:
  - jekyll-mentions
